<a href="https://colab.research.google.com/github/rahmani3101/Data-Science/blob/main/Pandas_Basicsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
one = pd.Series([1,2,3])
two = pd.Series([7,8,9])
result1=one+two #addition operation
print (result1)

0     8
1    10
2    12
dtype: int64

In [3]:
result2=one*two # multiplication operation
print (result2)

0     7
1    16
2    27
dtype: int64

In [5]:
import numpy as np
a=[np.arange(5)]
print(a)

[array([0, 1, 2, 3, 4])]

In [8]:
a=range(5)
print(a)

range(0, 5)

# Dataframe

A DataFrame is a two-dimensional labelled data structure like a table of MySQL. It contains rows and columns, and therefore has both a row and column index. Each column can have a different type of value such as numeric, string, boolean, etc., as in tables of a database.

Apandas Dataframe can be created using the following constructor :
pandas.DataFrame(data,index,columns,dtype,copy)

In [12]:
### Dataframe

pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [11]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

### Create DataFramefrom Lists

In [13]:
data = [1,2,3,4]
df = pd.DataFrame(data)
print (df)

   0
0  1
1  2
2  3
3  4

In [14]:
data = [['Anuj',20],['Bidhan',22],['Saroj',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print (df)

     Name  Age
0    Anuj   20
1  Bidhan   22
2   Saroj   13

In [16]:
data = [['Anuj',20],['Bidhan',22],['Saroj',13]]
df = pd.DataFrame(data,columns=['Name','Age'] ,dtype=str)
print (df)

     Name Age
0    Anuj  20
1  Bidhan  22
2   Saroj  13

### DataFrame from list of Dictionaries

In [17]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
print (df)

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [18]:
# Create a DataFrame by passing a list of dict and the row indices.
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, index=['first', 'second'])
print (df)

        a   b     c
first   1   2   NaN
second  5  10  20.0

In [19]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df1 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b'])
df2 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b1'])

In [20]:
df1

        a   b
first   1   2
second  5  10

df2 DataFrame is created with a column index other than the dictionary key; thus, appendedthe NaN’s in place. Whereas, df1 is createdwith columnindices same as dictionary keys, so NaN’s appended.

In [21]:
df2

        a  b1
first   1 NaN
second  5 NaN

In [22]:
data = {'Name':['Soham', 'Rohan', 'Sweta', 'Suman'],
        'Age':[25,24,28,32]}
df = pd.DataFrame(data)
print (df)

    Name  Age
0  Soham   25
1  Rohan   24
2  Sweta   28
3  Suman   32

In [23]:
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print (df)

        Name  Age
rank1  Soham   25
rank2  Rohan   24
rank3  Sweta   28
rank4  Suman   32

In [24]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

DataFrame from Dict of series

In [25]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

In [26]:
d

{'one': a    1
 b    2
 c    3
 dtype: int64,
 'two': a    1
 b    2
 c    3
 d    4
 dtype: int64}

In [27]:
df = pd.DataFrame(d)

for the series one, there is no label ‘d’ passed, but in the result, for the d label, NaNisappendedwithNaN.

In [28]:
df

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [29]:
d1 = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
      'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd']),
      'three': pd.Series([10,20,30],index=['a','b','c'])}
df1 = pd.DataFrame(d1)
df1

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

index=False or header=0 is required, without which there will be unnecessary index

In [30]:
df1.to_csv("abc.csv",index=False)
print (df1)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [31]:
df1= pd.read_csv("abc.csv")
print(df1)

   one  two  three
0  1.0    1   10.0
1  2.0    2   20.0
2  3.0    3   30.0
3  NaN    4    NaN

## Iterating a DataFrame

In [32]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
for col in df:
  print (col)

one
two

In [34]:
df = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
for key,value in df.items():
  print (key,value)

one a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64
two a    1
b    2
c    3
d    4
Name: two, dtype: int64

In [36]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
for row_index,row in df.iterrows():
  print (row_index,row)

a one    1.0
two    1.0
Name: a, dtype: float64
b one    2.0
two    2.0
Name: b, dtype: float64
c one    3.0
two    3.0
Name: c, dtype: float64
d one    NaN
two    4.0
Name: d, dtype: float64

In [37]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
for row in df.itertuples():
  print (row)

Pandas(Index='a', one=1.0, two=1)
Pandas(Index='b', one=2.0, two=2)
Pandas(Index='c', one=3.0, two=3)
Pandas(Index='d', one=nan, two=4)

In [38]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [39]:
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [40]:
df['two']

a    1
b    2
c    3
d    4
Name: two, dtype: int64

Column Addition to DataFrame

In [41]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print (df)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [44]:
# Adding a new column using the existing columns in DataFrame:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df['three'] = df['one'] + df['two']
print (df)

   one  two  three
a  1.0    1    2.0
b  2.0    2    4.0
c  3.0    3    6.0
d  NaN    4    NaN

Column Deletion from DataFrame

In [45]:
df

   one  two  three
a  1.0    1    2.0
b  2.0    2    4.0
c  3.0    3    6.0
d  NaN    4    NaN

In [46]:
del df['one']

In [47]:
df

   two  three
a    1    2.0
b    2    4.0
c    3    6.0
d    4    NaN

In [48]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
     'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df['three']=pd.Series([10,20,30],index=['a','b','c'])

In [49]:
df

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [51]:
df.pop('one')

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [52]:
df

   two  three
a    1   10.0
b    2   20.0
c    3   30.0
d    4    NaN

In [56]:
list1 = [1,2,3,4,5,6,2,3,2,2]
max(list1)

6

In [58]:
min(list1)

1

In [59]:
list1.reverse()

In [60]:
list1

[2, 2, 3, 2, 6, 5, 4, 3, 2, 1]

Wecan use the DataFrame.drop() method to delete rows and columns from a DataFrame. We need to specify the names of the labels to be dropped and the axis from which they need to be dropped. To delete a row, the parameter axis is assigned the value 0 and for deleting a column,the parameter axis is assigned the value 1.

In [61]:
d = {'one' : pd.Series([5,6,7,8], index=['row1', 'row2', 'row3','row4']), 'two' : pd.Series([1, 2, 3, 4], index=['row1', 'row2', 'row3','row4']), 'three' : pd.Series([9, 10, 3, 15], index=['row1', 'row2', 'row3','row4'])}

In [65]:
df = pd.DataFrame(d)
df

      one  two  three
row1    5    1      9
row2    6    2     10
row3    7    3      3
row4    8    4     15

In [66]:
df.drop('one',axis =1)

      two  three
row1    1      9
row2    2     10
row3    3      3
row4    4     15

In [67]:
df

      one  two  three
row1    5    1      9
row2    6    2     10
row3    7    3      3
row4    8    4     15

If the DataFrame has more than one row with the same label, the DataFrame.drop() method will delete all the matching rows from it.

In [68]:
df = df.drop('one',axis =1)

In [69]:
df

      two  three
row1    1      9
row2    2     10
row3    3      3
row4    4     15

Renaming column lebel of dataframe

In [70]:
d = {'one' : pd.Series([5,6,7,8], index=['row1', 'row2', 'row3','row4']), 'two' : pd.Series([1, 2, 3, 4], index=['row1', 'row2', 'row3','row4']), 'three' : pd.Series([9, 10, 3, 15], index=['row1', 'row2', 'row3','row4'])}
df = pd.DataFrame(d)

In [71]:
df

      one  two  three
row1    5    1      9
row2    6    2     10
row3    7    3      3
row4    8    4     15

In [72]:
df = df.rename({'one':'1','two':'2'}, axis='columns')

In [74]:
df

      1  2  three
row1  5  1      9
row2  6  2     10
row3  7  3      3
row4  8  4     15

Row Selection from dataframe

 Understanding `df.loc[]` and `df.iloc[]` for Data Selection

`df.loc[]` and `df.iloc[]` are two fundamental methods in Pandas for selecting data from a DataFrame. While both are used for selection, they operate based on different principles:

1.  **`df.loc[]` (Label-based indexing)**
    *   **Selects data by *explicit labels*** (names) of rows and columns.
    *   When slicing (e.g., `start:end`), *both the start and end labels are included* in the selection.
    *   It's ideal when you know the exact names of the rows or columns you want.

2.  **`df.iloc[]` (Integer-location based indexing)**
    *   **Selects data by *integer positions*** (0-based index) of rows and columns.
    *   Similar to standard Python slicing, when slicing (`start:end`), the `start` position is included, but the `end` position is *excluded*.
    *   It's useful when you want to select data based on its numerical position, regardless of its label.

Let's demonstrate these with the current DataFrame `df`.

In [76]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']), 'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [77]:
print (df.loc['a'])

one    1.0
two    1.0
Name: a, dtype: float64

In [78]:
df.iloc[1]

one    2.0
two    2.0
Name: b, dtype: float64

In [79]:
df.loc['e'] = [2,3]

In [80]:
df

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
e  2.0    3

In [81]:
df1 = pd.DataFrame([[1, 1], [2, 2], [3, 3]], columns = ['one','two'])
df2 = pd.DataFrame([[5], [7]], columns = ['three'])

In [82]:
df1

   one  two
0    1    1
1    2    2
2    3    3

In [83]:
df2

   three
0      5
1      7

In [85]:
df1 = pd.concat([df1, df2])
df1

   one  two  three
0  1.0  1.0    NaN
1  2.0  2.0    NaN
2  3.0  3.0    NaN
0  NaN  NaN    5.0
1  NaN  NaN    7.0

# Row Deletion from *dataframe*

We can use the DataFrame.drop() method to delete rows and columns from a DataFrame. We need to specify the names of the labels to be dropped and the axis from which they need to be dropped. To delete a row, the parameter axis is assigned the value 0 and for deleting a column,the parameter axis is assigned the value 1.

In [86]:
d = {'one' : pd.Series([5,6,7,8], index=['row1', 'row2', 'row3','row4']), 'two' : pd.Series([1, 2, 3, 4], index=['row1', 'row2', 'row3','row4']), 'three' : pd.Series([9, 10, 3, 15], index=['row1', 'row2', 'row3','row4'])}
df = pd.DataFrame(d)
print (df)

      one  two  three
row1    5    1      9
row2    6    2     10
row3    7    3      3
row4    8    4     15

In [87]:
df = df.drop('row2', axis=0)

If the DataFrame has more than one row with the same label, the DataFrame.drop() method will deleteall the matching rows from it.

In [88]:
df

      one  two  three
row1    5    1      9
row3    7    3      3
row4    8    4     15

In [89]:
d = {'one' : pd.Series([5,6,7,8], index=['row1', 'row2', 'row3','row4']), 'two' : pd.Series([1, 2, 3, 4], index=['row1', 'row2', 'row3','row4']), 'three' : pd.Series([9, 10, 3, 15], index=['row1', 'row2', 'row3','row4'])}
df = pd.DataFrame(d)
print (df)

      one  two  three
row1    5    1      9
row2    6    2     10
row3    7    3      3
row4    8    4     15

In [92]:
df = df.rename({'row1':'r1','row2':'r2','row3':'r3','English':'Sub4'}, axis='index')

The parameter axis='index' is used to specify that the row label is to be changed. If no new label is passed corresponding to an existing label, the existing row label is left as it is.

In [91]:
df

      one  two  three
r1      5    1      9
r2      6    2     10
r3      7    3      3
row4    8    4     15

In [93]:
d = {'one' : pd.Series([5,6,7,8,9,2], index=['row1', 'row2', 'row3','row4','row5','row6']), 'two' : pd.Series([1, 2, 3, 4,5,6], index=['row1', 'row2', 'row3','row4','row5','row6']), 'three' : pd.Series([9, 10, 3, 15,10,14], index=['row1', 'row2', 'row3','row4','row5','row6'])}
df = pd.DataFrame(d)

In [94]:
df.head()

      one  two  three
row1    5    1      9
row2    6    2     10
row3    7    3      3
row4    8    4     15
row5    9    5     10

In [95]:
df.head(2)

      one  two  three
row1    5    1      9
row2    6    2     10

In [96]:
df.tail(2)

      one  two  three
row5    9    5     10
row6    2    6     14

In [98]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
#retrieve the last three element
print (s.tail(3))

c    3
d    4
e    5
dtype: int64

In [100]:
s.tail(2)

d    4
e    5
dtype: int64

There are two ways of indexing Dataframes : Label based indexing and Boolean Indexing.

## Label Based Indexing

DataFrame.loc[] is an important method that is used for label based indexing with DataFrames.

In [103]:
d = {'one' : pd.Series([5,6,7,8], index=['row1', 'row2', 'row3','row4']), 'two' : pd.Series([1, 2, 3, 4], index=['row1', 'row2', 'row3','row4']), 'three' : pd.Series([9, 10, 3, 1], index=['row1', 'row2', 'row3','row4'])}
df = pd.DataFrame(d)
df

      one  two  three
row1    5    1      9
row2    6    2     10
row3    7    3      3
row4    8    4      1

In [104]:
print(df.loc['row2'])

one       6
two       2
three    10
Name: row2, dtype: int64

In [105]:
print(df.loc[['row2','row3']])

      one  two  three
row2    6    2     10
row3    7    3      3

In [107]:
print(df.loc[:,'two'])

row1    1
row2    2
row3    3
row4    4
Name: two, dtype: int64

In [109]:
print(df['two'])

row1    1
row2    2
row3    3
row4    4
Name: two, dtype: int64

## Boolean Indexing

In Boolean indexing, we can select the subsets of data based on the actual values in the DataFrame rather than their row/column labels. Thus, we can use conditions on column names to filter data values.

In [110]:
d = {'one' : pd.Series([5,6,7,8], index=['row1', 'row2', 'row3','row4']), 'two' : pd.Series([1, 2, 3, 4], index=['row1', 'row2', 'row3','row4']), 'three' : pd.Series([9, 10, 3, 1], index=['row1', 'row2', 'row3','row4'])}
df = pd.DataFrame(d)
df

      one  two  three
row1    5    1      9
row2    6    2     10
row3    7    3      3
row4    8    4      1

In [111]:
print(df.loc['row2'] > 3)

one       True
two      False
three     True
Name: row2, dtype: bool

In [112]:
print(df.loc[:,'two'] > 3)

row1    False
row2    False
row3    False
row4     True
Name: two, dtype: bool

## Joining, Merging and Concatenation of DataFrames

In [115]:
dF1=pd.DataFrame([[1, 2, 3], [4, 5],[6]], columns=['C1', 'C2', 'C3'], index=['R1','R2', 'R3'])
print(dF1)
dF2=pd.DataFrame([[10, 20], [30], [40,50]], columns=['C2', 'C5'], index=['R4', 'R2','R5'])
print(dF2)
dF1=pd.concat([dF1, dF2])
print(dF1)

    C1   C2   C3
R1   1  2.0  3.0
R2   4  5.0  NaN
R3   6  NaN  NaN
    C2    C5
R4  10  20.0
R2  30   NaN
R5  40  50.0
     C1    C2   C3    C5
R1  1.0   2.0  3.0   NaN
R2  4.0   5.0  NaN   NaN
R3  6.0   NaN  NaN   NaN
R4  NaN  10.0  NaN  20.0
R2  NaN  30.0  NaN   NaN
R5  NaN  40.0  NaN  50.0

### Using `pd.merge()` method

`pd.merge()` is used to combine DataFrames based on common columns or indices. It's similar to SQL JOIN operations. You can merge on one or multiple conditions (keys).

In [116]:
DF1 = pd.DataFrame({
    'id':[1,2,3],
    'Name': ['Ajay', 'Bijay', 'Sujoy'],
    'subject':['sub1','sub2','sub4']
})
DF2 = pd.DataFrame({
    'id':[1,2,3],
    'Name': ['Rakhi', 'Sakhi', 'Malini'],
    'subject':['sub1','sub5','sub4']
})

print("DF1:\n", DF1)
print("\nDF2:\n", DF2)

DF1:
    id   Name subject
0   1   Ajay    sub1
1   2  Bijay    sub2
2   3  Sujoy    sub4

DF2:
    id    Name subject
0   1   Rakhi    sub1
1   2   Sakhi    sub5
2   3  Malini    sub4

#### Joining with `merge()` on a single condition ('id')

In [117]:
print ("Merged on 'id':")
print (pd.merge(DF1, DF2, on='id'))

Merged on 'id':
   id Name_x subject_x  Name_y subject_y
0   1   Ajay      sub1   Rakhi      sub1
1   2  Bijay      sub2   Sakhi      sub5
2   3  Sujoy      sub4  Malini      sub4

#### Joining with `merge()` on two conditions ('id' and 'subject')

In [118]:
print ("\nMerged on ['id', 'subject']:")
print (pd.merge(DF1, DF2, on=['id','subject']))

Merged on ['id', 'subject']:
   id Name_x subject  Name_y
0   1   Ajay    sub1   Rakhi
1   3  Sujoy    sub4  Malini

### Using `pd.concat()` method

The `pd.concat()` function performs concatenation operations along an axis, either stacking DataFrames row-wise (axis=0, default) or column-wise (axis=1).

In [119]:
DF1 = pd.DataFrame({'id':[1,2,3], 'Name': ['Ajay', 'Bijay', 'Sujoy'], 'subject':['sub1','sub2','sub4']},index=[1,2,3])
DF2 = pd.DataFrame({'id':[1,2,3], 'Name': ['Rakhi', 'Sakhi', 'Malini'], 'subject':['sub1','sub5','sub4']},index=[1,2,3])

print("DF1 (for concat):\n", DF1)
print("\nDF2 (for concat):\n", DF2)

DF1 (for concat):
    id   Name subject
1   1   Ajay    sub1
2   2  Bijay    sub2
3   3  Sujoy    sub4

DF2 (for concat):
    id    Name subject
1   1   Rakhi    sub1
2   2   Sakhi    sub5
3   3  Malini    sub4

#### Joining with `concat()` with default axis (axis=0 - row-wise)

In [120]:
print ("\nConcatenated (axis=0, default):")
print (pd.concat([DF1,DF2]))

Concatenated (axis=0, default):
   id    Name subject
1   1    Ajay    sub1
2   2   Bijay    sub2
3   3   Sujoy    sub4
1   1   Rakhi    sub1
2   2   Sakhi    sub5
3   3  Malini    sub4

#### Joining with `concat()` with axis=1 (column-wise)

In [121]:
print ("\nConcatenated (axis=1):")
print (pd.concat([DF1,DF2],axis=1))

Concatenated (axis=1):
   id   Name subject  id    Name subject
1   1   Ajay    sub1   1   Rakhi    sub1
2   2  Bijay    sub2   2   Sakhi    sub5
3   3  Sujoy    sub4   3  Malini    sub4